name: Deploy to S3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      env:
        AWS_ACCESS_KEY_ID: AKIAZ4QMWYENVI2ITI2I
        AWS_SECRET_ACCESS_KEY: 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
        AWS_DEFAULT_REGION: eu-west-1 # Remplacez par votre région AWS (par exemple: us-east-1)
      run: |
        mkdir -p ~/.aws/
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
        echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
        echo "[default]" > ~/.aws/config
        echo "region=$AWS_DEFAULT_REGION" >> ~/.aws/config
    
    - name: Check directory content
      run: ls -al ./Curriculum-vitae-online

        
    - name: Deploy to S3
      run: |
        aws s3 sync ./Curriculum-vitae-online s3://cvenligne --delete
