name: Deploy to S3

on:
  push:
    paths:
      - '/freesavior/Curriculum-vitae-online/**'
  pull_request:
    paths:
      - '/freesavior/Curriculum-vitae-online/**'
  workflow_dispatch:
    
env:
  AWS_ACCESS_KEY_ID: AKIAZ4QMWYENVI2ITI2I
  AWS_SECRET_ACCESS_KEY: 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
  AWS_REGION: eu-west-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create AWS configuration directory
        run: mkdir -p ~/.aws

      - name: Set up AWS credentials
        run: |
          echo $AWS_ACCESS_KEY_ID > ~/.aws/credentials
          echo $AWS_SECRET_ACCESS_KEY >> ~/.aws/credentials
          echo $AWS_REGION >> ~/.aws/config

      - name: Deploy to S3
        run: aws s3 sync . s3://cvenligne --delete  # Change your-bucket-name to your actual S3 bucket name
